/* GENERATED by scripts/build_pages.py - do not edit the published copy.
 * API origin baked in at build time: https://tcstw.youngzyl.me:8444/linuxdo-api
 * Only apiBase selects an endpoint; optional readStateNamespace selects a localStorage
 * key, never a network destination. URL query strings select neither. */
window.LINUXDO_AI_RUNTIME = {"apiBase": "https://tcstw.youngzyl.me:8444/linuxdo-api", "readStateNamespace": "https://tcstw.youngzyl.me:8443/linuxdo-api"};
