/* GENERATED by scripts/build_pages.py - do not edit the published copy.
 * API origin baked in at build time: https://tcstw.youngzyl.me:8443/linuxdo-api
 * The page reads `apiBase` and nothing else; the URL query string is never used to
 * pick an endpoint. Rebuild and redeploy to change it. */
window.LINUXDO_AI_RUNTIME = {"apiBase": "https://tcstw.youngzyl.me:8443/linuxdo-api"};
