#!/usr/bin/env python3
"""Build the static frontend for GitHub Pages.

    python3 scripts/build_pages.py --api-base https://tcstw.youngzyl.me:8444/linuxdo-api \
                                   --read-state-namespace https://tcstw.youngzyl.me:8443/linuxdo-api \
                                   --out /tmp/linuxdo-pages-build

GitHub Pages serves files only, so the published copy cannot use relative `/api/...` calls.
This script writes exactly the files the page needs - index.html, app.js, styles.css and a
*runtime-config.js generated here* that carries the API origin - plus `.nojekyll`:

  * `apiBase` and optional `readStateNamespace` are validated (absolute http(s), https
    unless it is a localhost dev origin, no query/fragment/credentials). The latter is only
    a browser-local read-state key, never a network destination. The frontend never
    accepts an API origin from the query string, so a crafted link cannot redirect the page
    or the owner token it holds.
  * nothing else is copied: no fixtures, no data/, no docs/, no .env, no logs. The copy list
    is an allowlist and the result is verified afterwards.
  * the owner token is a server-side secret and is never part of a build.

Every write goes to `--out`, which must not be the repository, `public/` or any ancestor of
them. Prints a JSON manifest (path, bytes, sha256) for the deploy evidence.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "public"

# The complete set of files the published site is allowed to contain. Anything else in
# public/ (fixtures/, for instance) is deliberately not part of a build.
SOURCES = ("index.html", "app.js", "styles.css")

MANIFEST_NAME = ".nojekyll"
LOCAL_HOSTS = ("localhost", "127.0.0.1", "[::1]", "::1")

# The only entries a --out directory may already hold when it is reused. A reused --out must
# contain nothing but this build's own output: an extra file, a nested directory (a stale
# `fixtures/`, say) or a symlink would otherwise be silently preserved into a published
# bundle, which is exactly how a stray fixture or a stale asset reaches the site.
ALLOWED_ENTRIES = frozenset(SOURCES) | {"runtime-config.js", MANIFEST_NAME}


class BuildError(RuntimeError):
    pass


def validate_api_base(raw: str) -> str:
    """Return the canonical API base or raise BuildError.

    Requires an absolute http(s) URL with a host, no credentials, no query and no fragment;
    https everywhere except a localhost dev origin.
    """
    text = (raw or "").strip()
    if not text:
        raise BuildError("--api-base is required (the published page cannot use relative /api URLs)")
    try:
        parts = urlsplit(text)
    except ValueError as exc:
        raise BuildError(f"--api-base is not a valid URL: {exc}") from None
    scheme = (parts.scheme or "").lower()
    if scheme not in ("http", "https"):
        raise BuildError(f"--api-base must be an absolute http(s) URL, got {raw!r}")
    if not parts.hostname:
        raise BuildError(f"--api-base needs a host, got {raw!r}")
    if parts.username or parts.password:
        raise BuildError("--api-base must not carry credentials in the URL")
    if parts.query or parts.fragment:
        raise BuildError("--api-base must be a base URL: no query string, no fragment")
    if scheme == "http" and parts.hostname.lower() not in LOCAL_HOSTS:
        raise BuildError("--api-base must use https (plain http is only allowed for a localhost dev origin)")
    return text.rstrip("/")


def runtime_config_js(api_base: str, read_state_namespace: str | None = None) -> str:
    """Generated config; optional namespace affects only browser-local read state."""
    config = {"apiBase": api_base}
    if read_state_namespace is not None:
        config["readStateNamespace"] = read_state_namespace
    return (
        "/* GENERATED by scripts/build_pages.py - do not edit the published copy.\n"
        f" * API origin baked in at build time: {api_base}\n"
        " * Only apiBase selects an endpoint; optional readStateNamespace selects a localStorage\n"
        " * key, never a network destination. URL query strings select neither. */\n"
        "window.LINUXDO_AI_RUNTIME = " + json.dumps(config, ensure_ascii=False) + ";\n"
    )


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _guard_out_dir(out: Path) -> Path:
    target = out.expanduser().resolve()
    protected = [ROOT.resolve(), PUBLIC.resolve()]
    for path in protected:
        if target == path or path in target.parents:
            raise BuildError(f"--out {target} would overwrite the source tree ({path}); pick a separate directory")
    if target == Path(target.anchor):
        raise BuildError(f"--out {target} is a filesystem root")
    return target


def _check_reusable_out(out: Path) -> None:
    """Refuse a reused --out that holds anything this build does not write itself.

    Checked *before* anything is written, so a refused build leaves the directory exactly as
    it found it. Directories and symlinks are refused by kind, not by name: writing through a
    symlink (or into a nested tree) would publish content this build never produced.
    """
    if not out.exists():
        return
    if not out.is_dir():
        raise BuildError(f"--out {out} exists and is not a directory")
    unexpected = []
    for entry in sorted(out.iterdir(), key=lambda p: p.name):
        if entry.is_symlink():
            unexpected.append(f"{entry.name} (symlink)")
        elif entry.is_dir():
            unexpected.append(f"{entry.name}/")
        elif entry.name not in ALLOWED_ENTRIES:
            unexpected.append(entry.name)
    if unexpected:
        raise BuildError(
            f"--out {out} is a reused directory holding entries this build does not write: "
            + ", ".join(unexpected)
            + "; point --out at an empty directory"
        )


def build(api_base_raw: str, out_dir: str | Path, read_state_namespace: str | None = None) -> dict:
    """Write the publishable site and return the manifest."""
    api_base = validate_api_base(api_base_raw)
    namespace = validate_api_base(read_state_namespace) if read_state_namespace is not None else None
    out = _guard_out_dir(Path(out_dir))
    _check_reusable_out(out)

    for name in SOURCES + ("runtime-config.js",):
        if not (PUBLIC / name).is_file():
            raise BuildError(f"missing source file: public/{name}")

    out.mkdir(parents=True, exist_ok=True)
    files: list[dict] = []

    for name in SOURCES:
        data = (PUBLIC / name).read_bytes()
        (out / name).write_bytes(data)
        files.append({"path": name, "bytes": len(data), "sha256": _sha256(data)})

    generated = runtime_config_js(api_base, namespace).encode("utf-8")
    (out / "runtime-config.js").write_bytes(generated)
    files.append({"path": "runtime-config.js", "bytes": len(generated), "sha256": _sha256(generated), "generated": True})

    jekyll = b""
    (out / ".nojekyll").write_bytes(jekyll)
    files.append({"path": ".nojekyll", "bytes": 0, "sha256": _sha256(jekyll), "generated": True})

    expected = {entry["path"] for entry in files}
    written = {p.name for p in out.iterdir()}
    extra = sorted(written - expected)
    if extra:
        raise BuildError(f"refusing to publish unexpected entries: {extra}")

    # a build must never contain a credential, whatever the environment holds
    leaked = _scan_for_secrets(out)
    if leaked:
        raise BuildError("build output looks like it contains a secret; aborting: " + ", ".join(leaked))

    return {"out": str(out), "api_base": api_base, "files": files, "total_bytes": sum(f["bytes"] for f in files)}


def _scan_for_secrets(out: Path) -> list[str]:
    """Look for credentials in the build output.

    Two kinds of probe: the *values* of credential-ish environment variables (so a canary
    in the environment cannot ride along), and key-shaped literals. Plain strings like the
    header name `Bearer ` or a CSS class `sk-…` are not secrets and must not trip this.
    """
    import os

    values = []
    for env_name in ("LINUXDO_AI_OWNER_TOKEN", "DEEPSEEK_API_KEY", "COMMANDCODE_APIKEY", "LINUXDO_AI_FILTER_API_KEY"):
        value = os.environ.get(env_name)
        if value and len(value) >= 8:
            values.append(value)
    shapes = [
        re.compile(r"sk-[A-Za-z0-9_\-]{16,}"),
        re.compile(r"Bearer\s+[A-Za-z0-9._\-]{20,}"),
        re.compile(r"(?i)(commandcode_apikey|owner_token|api_key)\s*=\s*\S{8,}"),
    ]
    found = []
    for path in sorted(out.iterdir()):
        if not path.is_file():
            continue
        text = path.read_bytes().decode("utf-8", "replace")
        hit = next((value for value in values if value in text), None)
        if hit:
            found.append(f"{path.name} contains a credential value from the environment")
            continue
        if any(pattern.search(text) for pattern in shapes):
            found.append(f"{path.name} contains a key-shaped literal")
    return found


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="build the GitHub Pages bundle of the linux.do AI feed")
    parser.add_argument("--api-base", required=True, help="absolute https origin of the API (the Caddy path suffix is kept)")
    parser.add_argument("--read-state-namespace", help="optional validated old API base used only for the browser-local read-state key")
    parser.add_argument("--out", required=True, help="output directory (must not be the repo or public/)")
    parser.add_argument("--quiet", action="store_true", help="only print the manifest")
    args = parser.parse_args(argv)
    try:
        manifest = build(args.api_base, args.out, read_state_namespace=args.read_state_namespace)
    except BuildError as exc:
        print(f"build failed: {exc}", file=sys.stderr)
        return 2
    if not args.quiet:
        print(f"built {len(manifest['files'])} files into {manifest['out']}", file=sys.stderr)
        print(f"api base: {manifest['api_base']}", file=sys.stderr)
    print(json.dumps(manifest, ensure_ascii=False, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
